train: /home/yakov/Pedanteq/tracking/Basketball-shot-detection/dataset/train/images
val: /home/yakov/Pedanteq/tracking/Basketball-shot-detection/dataset/valid/images
test: /home/yakov/Pedanteq/tracking/Basketball-shot-detection/dataset/test/images

# replace '...' with your local absolute paths
# download the dataset used here: https://universe.roboflow.com/034-ganesh-kumar-m-v-cs-r2lwe/basketball-lhqoe/dataset/1

nc: 2
names: ['Basketball', 'Basketball Hoop']
